services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 15s
      timeout: 20s
      retries: 10
  server:
    build: 
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - PORT
    ports: 
      - "${PORT}:${PORT}"
    depends_on:
      db: 
        condition: service_healthy
  # testing:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=test
  #   ports:
  #     - 5431:5432
volumes:
  pg-db:
