CREATE CAST (CHARACTER varying  AS ACCOUNT_TYPE) WITH INOUT AS ASSIGNMENT;
CREATE CAST (CHARACTER varying AS ACCOUNT_STATUS) WITH INOUT AS ASSIGNMENT;
CREATE CAST (CHARACTER varying AS TRANSACTION_TYPE) WITH INOUT AS ASSIGNMENT;
